name: Build and Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: arm-unknown-linux-gnueabihf

      - name: Download and extract kindlehf toolchain
        run: |
          curl -L https://github.com/koreader/koxtoolchain/releases/download/2025.05/kindlehf.tar.gz \
            | tar -xz

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Prepare Release
        run: cargo build --target arm-unknown-linux-gnueabihf --release

      - name: Package extension
        run: |
          mkdir -p AnkiKindle/bin

          cp target/arm-unknown-linux-gnueabihf/release/anki-kindle AnkiKindle/bin/anki-kindle

          cp kindle_scripts/launch.sh AnkiKindle/bin/launch.sh
          cp kindle_scripts/kill.sh AnkiKindle/bin/kill.sh
          cp kindle_scripts/install_browser.sh AnkiKindle/bin/install_browser.sh
          cp kindle_scripts/restore_browser.sh AnkiKindle/bin/restore_browser.sh
          cp kindle_scripts/browser AnkiKindle/bin/browser
          cp kindle_scripts/menu.json AnkiKindle/menu.json
          cp kindle_scripts/config.xml AnkiKindle/config.xml

          chmod +x AnkiKindle/bin/launch.sh
          chmod +x AnkiKindle/bin/kill.sh
          chmod +x AnkiKindle/bin/install_browser.sh
          chmod +x AnkiKindle/bin/restore_browser.sh
          chmod +x AnkiKindle/bin/browser

          zip -r anki-kindle.zip AnkiKindle/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "anki-kindle.zip"
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
